# Generated by Django 5.0.6 on 2024-08-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computerName', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('graphic', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
