# Generated by Django 5.0.6 on 2024-08-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0002_computer_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='hdd',
            field=models.CharField(default='hdd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor',
            field=models.CharField(default='monitor', max_length=100),
            preserve_default=False,
        ),
    ]
