# Generated by Django 5.0.6 on 2024-08-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0003_computer_hdd_computer_monitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('resolation', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Computer',
        ),
    ]
