# Generated by Django 5.0.6 on 2024-08-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0004_tv_delete_computer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Tv',
        ),
    ]
