# Generated by Django 5.0.6 on 2024-08-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0006_mobile_delete_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=20)),
                ('computer_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cpu', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('graphic', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_name', models.CharField(max_length=20)),
                ('monitor_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fullhd', models.BooleanField(default=False)),
                ('oled', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
