# Generated by Django 5.0.6 on 2024-08-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0008_alter_computer_computer_price_alter_monitor_fullhd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computerId', models.IntegerField()),
                ('computerUserName', models.CharField(max_length=20)),
                ('computerText', models.TextField(max_length=500)),
                ('computerCreated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitorId', models.IntegerField()),
                ('monitorUserName', models.CharField(max_length=20)),
                ('monitorText', models.TextField(max_length=500)),
                ('monitorCreated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
