# Generated by Django 5.0.6 on 2024-08-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0009_computercomment_monitorcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ComputerComment',
        ),
        migrations.DeleteModel(
            name='MonitorComment',
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_price',
            field=models.IntegerField(),
        ),
    ]
