# Generated by Django 5.0.6 on 2024-09-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0011_comment_computer_id_alter_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='computer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
