# Generated by Django 5.0.6 on 2024-09-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0012_remove_comment_id_alter_comment_computer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='computer_id',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
