# Generated by Django 5.0.6 on 2024-09-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0013_comment_id_alter_comment_computer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='monitor_id',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
