# Generated by Django 5.0.6 on 2024-09-05 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0014_comment_monitor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='computer_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='monitor_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='greeting.computer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='greeting.monitor'),
        ),
    ]
